name: tfmr_gpu
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - jupyter=1.0.0
  - tensorflow-gpu=1.12.0
  - tensorflow-hub=0.2.0
  - seaborn=0.9.0
  - scikit-learn=0.20.2
  - keras=2.2.4

