version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda

    working_directory: ~/tfmr

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml
            source activate tfmr

      - run:
          name: run tests
          command: |
            source activate tfmr
            python -m unittest discover -s tests

